open Model
open Printer_tools


(* -------------------------------------------------------------------------- *)
let pp_model fmt (_model : model) =
  Format.fprintf fmt "// Solidity output generated by %a@."
    pp_bin ()


(* -------------------------------------------------------------------------- *)
let string_of__of_pp pp x =
  Format.asprintf "%a@." pp x

let show_model (x : model) = string_of__of_pp pp_model x
