open Model
open Printer_tools


(* -------------------------------------------------------------------------- *)
let pp_model fmt (_model : model) =
  let pp_version fmt _ =
    Format.fprintf fmt "%a" pp_str Options.version
  in
  Format.fprintf fmt "// Solidity output generated by archetype %a@."
    pp_version ()


(* -------------------------------------------------------------------------- *)
let string_of__of_pp pp x =
  Format.asprintf "%a@." pp x

let show_model (x : model) = string_of__of_pp pp_model x
