# This is a basic workflow that is manually triggered

name: Archetype compiler CI

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - 4.10.2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - run: sudo add-apt-repository ppa:serokell/tezos && sudo apt-get update

    - run: sudo apt-get install -y apt-transport-https tezos-client

    # Runs a single command using the runners shell
    - name: Use OCaml ${{ matrix.ocaml-compiler }}
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}

    - run: opam install . --deps-only --with-test

    - run: opam exec -- dune build

    - run: ./extra/script/check_mockup.sh
